name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

defaults:
  run:
    working-directory: .docker

env:
  node_version: "16.x"
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_FILE: "Dockerfile.github"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        cp ../.env.example ../.env
        docker-compose build
        docker-compose run --rm web sh -c 'exit 0'
    - name: Lint
      run: docker-compose run --rm web yarn lint

#  test:
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    steps:
#    - uses: actions/checkout@v2
#    - name: Setup
#      run: |
#        cp .env.example .env
#        docker-compose build
#        docker-compose run --rm web sh -c 'exit 0'
#        docker-compose up --detach
#    - name: Unit test
#      run: docker-compose exec -T web yarn test
#    - name: E2E test
#      run: docker-compose exec -T web yarn test:e2e

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        cp ../.env.example ../.env
        docker-compose build
        docker-compose run --rm web sh -c 'exit 0'
    - name: Build
      run: docker-compose run --rm web yarn build

  build-and-upload-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    outputs:
      docker-tag: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: .docker/Dockerfile.prod
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
